title: CV | A jekyll template
description:  A beautiful template for your CV.
url: https://carlos.asesoreducativo.mx/
baseurl: '/'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
