title: CV | Carlos Manuel Chee Vázuqez
description:  Currículum vitae de Carlos Manuel Chee Vázquez
url: https://carlos.asesoreducativo.mx/
baseurl: '/'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
